theme: jekyll-theme-cayman
title: "Paul Atkins - Introduction to Information Technology SP1 2019"
desc: This is Assignment 1 for subject introduction to information technology
author: paulatkins88@gmail.com
github_username: PaulAtkins88
twitter_username: @paul070781