theme: jekyll-theme-cayman
url: "https://PaulAtkins88.github.io"
baseurl: ""
title: Paul Atkins - Introduction to Information Technology SP1 2019
desc: This is Assignment 1 for subject introduction to information technology
author: paulatkins88@gmail.com
name: Paul Atkins
#social-network-links:
#rss: true
#github: PaulAtkins88
#twitter: @paul070781
#share-links-active:
#twitter: true
#facebook: true