theme: jekyll-theme-cayman
title: Paul Atkins - Introduction to Information Technology SP1 2019

[My Personal Info](personalinfo)

desc: This is Assignment 1 for subject introduction to information technology
